import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

from omavalet import render_lua


class RenderLuaTest(unittest.TestCase):
    def test_parks_enabled_app_without_launching_at_login(self):
        lua = render_lua(
            {
                "apps": [
                    {
                        "name": "Firefox",
                        "class": "firefox",
                        "exec": "firefox",
                        "workspace": 2,
                        "enabled": True,
                        "silent": True,
                    }
                ]
            }
        )

        self.assertIn(
            'o.window("firefox", { workspace = "2" })', lua
        )
        self.assertNotIn("launch_on_start", lua)
        self.assertTrue(
            lua.startswith(
                "-- Generated by io.github.jcarcinogen.omavalet. Do not edit."
            )
        )

    def test_launch_on_start_is_opt_in(self):
        lua = render_lua(
            {
                "apps": [
                    {
                        "name": "Firefox",
                        "class": "firefox",
                        "exec": "firefox",
                        "workspace": 2,
                        "launchOnStart": True,
                    }
                ]
            }
        )

        self.assertIn('o.window("firefox", { workspace = "2" })', lua)
        self.assertIn(
            'o.exec_on_start("[workspace 2 silent] uwsm-app -- firefox")', lua
        )

    def test_rejects_workspace_outside_valet_lot(self):
        with self.assertRaisesRegex(ValueError, "workspace must be between 1 and 10"):
            render_lua(
                {
                    "apps": [
                        {
                            "class": "firefox",
                            "exec": "firefox",
                            "workspace": 0,
                        }
                    ]
                }
            )

    def test_parking_slips_render_in_workspace_then_name_order(self):
        lua = render_lua(
            {
                "apps": [
                    {"name": "Zoom", "class": "zoom", "exec": "zoom", "workspace": 3},
                    {"name": "Brave", "class": "brave", "exec": "brave", "workspace": 1},
                    {"name": "Alacritty", "class": "alacritty", "exec": "alacritty", "workspace": 1},
                ]
            }
        )

        self.assertLess(
            lua.index('o.window("alacritty"'), lua.index('o.window("brave"')
        )
        self.assertLess(lua.index('o.window("brave"'), lua.index('o.window("zoom"'))

    def test_escapes_quotes_and_newlines_in_lua_strings(self):
        lua = render_lua(
            {
                "apps": [
                    {
                        "name": "Odd",
                        "class": 'app"class',
                        "exec": 'foo --title "Hi"\nbar',
                        "workspace": 1,
                    }
                ]
            }
        )

        self.assertIn(
            'o.window("app\\"class", { workspace = "1" })', lua
        )
        self.assertNotIn("launch_on_start", lua)


if __name__ == "__main__":
    unittest.main()
